sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.2

install:
  - bundle install

before_script:
  - git config --global user.email "window3809@naver.com"
  - git config --global user.name "brandnewkorean"

#script: bundle exec rake site:deploy --quiet #--trace

env:
  global:
    secure: "c+FYI9nMwq3271+e2PtXlehSatDJ2WxzkuAUlxKAMsAZByn9fEYh/io0GLEBUqgf+RfX8VBPflEIiVNUg/kiMSEjop7XyFrSG5HIklmkS0gw0K8ZsDbflp8i3rFojb+TtB5Q5VYiP0fq4Y+evGC4EwB3TJ28YtcjR+5+/ma5V9ZLr4+oS95GvKcg/iH/JXO0/PN7v/mHkCsl0n9JPFDzwJQ3gHHVvfh1LIVgk7vmKgiPwF76+H/w2tB9TmP4UaO9bvvBm96i5weH4op7iL3abaBNwlE18k318KtHTjD4JPrk41H1/e+SSYpMXhx/30BAZ/xHIA0kD3DcX3BQm4XWyMKTOrCOJZInB6rfrvRs2peqonIAZ4GTq47UgwOfaMwR03gw/VlyhpUQtpzgJKd8guND4TsgPIT8ac0rX0iJegF+vMY1nK7vIf8sYd1I0Buv2zUrTXHypV9cmWcWEeCkRSWXc34VqOmTCatbbFszOMtY8dBdpsC5kQeR3p7A+4WmGmg2HRp9VmMjS1t2htTTR7/bF76MB/XQ5Oq2kAg6QVz7/DDjiks+YNuTowxaNGDKref3x1ctpZ/YOTVUHHD2nzpM2LKlAOp8wHAUgQ5R2eXEyBABse9wa3Aa+DbaDCaruUKLbu822tcUZTMj4EFjvHoE/vBY5+2mqk4wdD1RF8w="
branches:
  only:
    - main
